modLoader = "javafml"
loaderVersion = "[36,)"
#issueTrackerURL = ""
license = "Apache 2.0"

[[mods]]
modId = "cosmetica_core"
version = "${version}"
displayName = "Cosmetica Core"
authors = "Valoeghese"
description = '''
Authenticates users with the Cosmetica servers and shows cool cosmetics on players.
'''
#logoFile = ""

[[dependencies.cosmetica_core]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cosmetica_core]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.1,)"
ordering = "NONE"
side = "BOTH"
