org.gradle.jvmargs=-Xmx2048M

minecraft_version=26.1
enabled_platforms=fabric,forge,neoforge

archives_base_name=cosmetica-core
mod_version=2.1.6
maven_group=cc.cosmetica

fabric.loom.disableObfuscation=true

# Loader-Specific
fabric_loader_version=0.18.4
fabric_api_version=0.144.3+26.1

forge_version=26.1-62.0.3
neoforge_version=26.1.0.1-beta

# Dependencies
cosmetica_java_client_version=0.45.0-0.0.0
