org.gradle.jvmargs=-Xmx2048M

minecraft_version=1.18.2
enabled_platforms=fabric,forge

archives_base_name=cosmetica-core
mod_version=2.1.6
maven_group=cc.cosmetica

fabric_loader_version=0.18.4
fabric_api_version=0.58.0+1.18.2

forge_version=1.18.2-40.1.14

cosmetica_java_client_version=0.45.0-0.0.0
