org.gradle.jvmargs=-Xmx2048M

minecraft_version=1.21.4
enabled_platforms=fabric,forge,neoforge

archives_base_name=cosmetica-core
mod_version=2.1.3
maven_group=cc.cosmetica

# Loader-Specific
fabric_loader_version=0.18.4
fabric_api_version=0.110.5+1.21.4

forge_version=1.21.4-54.1.0

neoforge_version=21.4.84-beta

# Dependencies
cosmetica_java_client_version=0.45.0-0.0.0
