plugins {
    id "com.github.johnrengelman.shadow" version "8.1.1"
}

architectury {
    platformSetupLoomIde()
    forge()
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath

    forge {
        convertAccessWideners = true
        extraAccessWideners.add loom.accessWidenerPath.get().asFile.name

        mixinConfig "cosmetica-core-common.mixins.json"
        mixinConfig "cosmetica-core-forge.mixins.json"
    }
}

configurations {
    common
    shadowCommon // Don't use shadow from the shadow plugin since it *excludes* files.
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common
}

dependencies {
    forge "net.minecraftforge:forge:${rootProject.forge_version}"

    api "gg.cloaks:javaclient:${cosmetica_java_client_version}"

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionForge")) { transitive = false }

    // bundle okhttp and javaclient
    shadow "gg.cloaks:javaclient:${cosmetica_java_client_version}"

    // Java 11+ doesn't bundle these by default
    // Source: https://mvnrepository.com/artifact/javax.xml.bind/jaxb-api
    // Source: https://mvnrepository.com/artifact/javax.activation/javax.activation-api
    shadow "javax.xml.bind:jaxb-api:2.4.0-b180830.0359"
    shadow "javax.activation:javax.activation-api:1.2.0"
}

processResources {
    inputs.property "version", project.version

    filesMatching("META-INF/mods.toml") {
        expand "version": project.version
    }
}

shadowJar {
    exclude "fabric.mod.json"
    exclude "architectury.common.json"

    relocate 'com.fasterxml.jackson', 'cc.cosmetica.com.fasterxml.jackson'
    relocate 'org.openapitools.jackson', 'cc.cosmetica.org.openapitools.jackson'
    relocate 'org.apache.hc', 'cc.cosmetica.org.apache.hc'
    relocate 'org.slf4j', 'cc.cosmetica.org.slf4j'
    exclude 'javax/annotation/**'
    exclude 'org/apache/commons/**'

    relocate 'javax.activation', 'cc.cosmetica.include.javax.activation'
    relocate 'javax.xml', 'cc.cosmetica.include.javax.xml'

    mergeServiceFiles()

    configurations = [project.configurations.shadowCommon, project.configurations.shadow]
    archiveClassifier = "dev-shadow"
}

remapJar {
    input.set shadowJar.archiveFile
    dependsOn shadowJar
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

publishing {
    publications {
        mavenForge(MavenPublication) {
            artifactId = rootProject.archives_base_name + "-" + project.name
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        if (System.getenv("COSMETICA_MAVEN_PASSWORD") != null) {
            maven {
                url = "https://maven.cloaks.gg/releases"
                credentials {
                    username = System.getenv("COSMETICA_MAVEN_USERNAME")
                    password = System.getenv("COSMETICA_MAVEN_PASSWORD")
                }
            }
        }
    }
}
