modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/Cosmetica-cc/cosmetica-core/issues"
license = "Apache 2.0"

[[mods]]
modId = "cosmetica_core"
version = "${version}"
displayName = "Cosmetica Core"
authors = "Valoeghese"
description = '''
Authenticates users with the Cosmetica servers and shows cool cosmetics on players.
'''
#logoFile = ""

[[dependencies.cosmetica_core]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cosmetica_core]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.21.4)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "cosmetica-core-common.mixins.json"

[[mixins]]
config = "cosmetica-core-neoforge.mixins.json"